kind: pipeline
name: default

- name: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.0
  commands:
  - cd src
  - dotnet build Allure.XUnit.sln -c Release

- name: push
  image: mcr.microsoft.com/dotnet/core/sdk:2.0
  environment:
    NUGET_APIKEY:
      from_secret: NUGET_API
  commands:
  - cd src
  - dotnet pack  Allure.XUnit/Allure.XUnit.csproj -c Release  /p:PackageVersion=$DRONE_TAG
  - dotnet nuget push **/Allure.XUnit.*.nupkg -k $NUGET_APIKEY -s https://www.nuget.org
  when:
    event:
    - tag

trigger:
  event:
  - pull_request
  - push
  - tag

