language: csharp
mono: none
dotnet: 2.0
install:
- dotnet restore
script:
- dotnet build -c Release
before_deploy:
- dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push ./src/Allure.XUnit/bin/Release/netcoreapp2.0/Allure.XUnit.*.nupkg -k $NUGET_API -s https://api.nuget.org/v3/index.json --skip-duplicate
  on:
    branch: master